{
   "category":"tracker",
   "request":"get",
   "statuscode":200,
   "values":{
      "frame":{
         "avg":{
            "x":0.0,
            "y":0.0
         },
         "fix":false,
         "lefteye":{
            "avg":{
               "x":0.0,
               "y":0.0
            },
            "pcenter":{
               "x":0.0,
               "y":0.0
            },
            "psize":0.0,
            "raw":{
               "x":0.0,
               "y":0.0
            }
         },
         "raw":{
            "x":0.0,
            "y":0.0
         },
         "righteye":{
            "avg":{
               "x":0.0,
               "y":0.0
            },
            "pcenter":{
               "x":0.0,
               "y":0.0
            },
            "psize":0.0,
            "raw":{
               "x":0.0,
               "y":0.0
            }
         },
         "state":16,
         "time":319162402,
         "timestamp":"2018-04-04 19:37:48.834"
      }
   }
}